# Generated by Django 3.2.12 on 2023-12-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='oras',
            field=models.CharField(default='Nedefinit', max_length=255),
        ),
        migrations.AddField(
            model_name='element',
            name='tara',
            field=models.CharField(default='Nedefinit', max_length=255),
        ),
    ]
