# Generated by Django 3.2.12 on 2023-12-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0002_auto_20231225_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='transport',
            field=models.CharField(default='Nedefinit', max_length=255),
        ),
    ]
